name: deploy to production
# on:
#   push:
#     branches:
#       - 'staging'
#       - 'main'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: "${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
          ls -l ${{ github.workspace }}